<?php

/**
 * Implements hook_permission().
 */
function worx_social_review_permission() {
  return array(
    'social review email' => array(
      'title' => t('Social Review Email'),
      'description' => t('Send social review emails'),
    )
  );
}

/** 
 * implements hook_menu().
 */
function worx_social_review_menu() {
  $items['admin/config/worx_features/social'] = array(
    'title' => 'Social Links',
    'description' => 'Set initial links for Social Review',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_settings_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review.admin.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/social/general'] = array(
    'title' => 'General Settings',
    'description' => 'Set initial links for Social Review',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_settings_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review.admin.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/social_review/email'] = array(
    'title' => 'Social Review Email',
    'description' => 'Send review links email',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_email_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review_email_form.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/social_review/email/general'] = array(
    'title' => 'Social Review Email Form',
    'description' => 'Send review links email',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_email_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review_email_form.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/social_review/email/template'] = array(
    'title' => 'Social Review Email Template',
    'description' => 'Adjust email template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('worx_social_review_email_template_form'),
    'access arguments' => array('social review email'),
    'file' => 'worx_social_review_email_template_form.inc',
    'file path' => drupal_get_path('module', 'worx_social_review'),
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Implements hook_mail().
 */
function worx_social_review_mail($key, &$message, $params) {
  switch ($key) {
    case 'social_review':
      //Old code that did not work
      //$message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      //New code taken directly from API docs; changed plain to html
      $headers = array(
        'MIME-Version' => '1.0', 
        'Content-Type' => 'text/html; charset=UTF-8; format=flowed; delsp=yes', 
        'Content-Transfer-Encoding' => '8Bit', 
        'X-Mailer' => 'Drupal',
      );
      $message['subject'] = $params['subject'];
      $token_replace = str_replace(
        $search = array(
          '[google]',
          '[yahoo]',
          '[bing]',
          '[yp]',
          '[foursquare]',
          '[urbanspoon]',
          '[ta]',
        ),
        $replace = array(
          $params['google'],
          $params['yahoo'],
          $params['bing'],
          $params['yp'],
          $params['foursquare'],
          $params['urbanspoon'],
          $params['ta'],
        ),
        $subject = $params['body']
      );
      $message['body'] = array($token_replace);
      break;
  }
}